### ISSUE TITLE
geodesic distance calculation

### ISSUE THREAD

**Issue by lixiang-ucas** [OshriHalimi/unsupervised_learning_of_dense_shape_correspondence#1]
Dear OShri, can you please provide the source file for compiling the file 'Tools/fastmarchmex.mexw64'.  The file provided seems working on windows but not for Linux system.

**Comment by orlitany** [comment]
Thanks for you interest in the project,  @lixiang-ucas . I have uploaded 2 versions i found, complied for mac and linux. Hopefully these will work for you.

**Comment by lixiang-ucas** [comment]
Thanks for your quick reply @orlitany. I have tried your mex file but encountered an error when the mex running. I'm using Ubuntu 16.04, matlab R2017b. Detail configurations are listed below:

Configuration:
  Crash Decoding      : Disabled - No sandbox or build area path
  Crash Mode          : continue (default)
  Current Graphics Driver: NVIDIA Corporation TITAN Xp/PCIe/SSE2 Version 4.5.0 NVIDIA 384.130
  Current Visual      : 0x21 (class 4, depth 24)
  Default Encoding    : UTF-8
  Deployed            : false
  GNU C Library       : 2.23 stable
  Host Name           : ubuntu
  MATLAB Architecture : glnxa64
  MATLAB Entitlement ID: 6257193
  MATLAB Root         : /media/ubuntu/MyHome/matlab
  MATLAB Version      : 9.3.0.713579 (R2017b)
  OpenGL              : hardware
  Operating System    : Linux 4.15.0-60-generic #67~16.04.1-Ubuntu SMP Mon Aug 26 08:57:33 UTC 2019 x86_64
  Processor ID        : x86 Family 6 Model 85 Stepping 4, GenuineIntel
  Virtual Machine     : Java 1.8.0_121-b13 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
  Window System       : The X.Org Foundation (11906000), display :0

**Comment by lixiang-ucas** [comment]
generate all data using windows already.

**Comment by lixiang-ucas** [comment]
Dear OShri, sorry to bother you again. The mex files you give can process the synthetic shapes but reports a bug and the Matlab exit when processing downsampled real scans. I encountered this problem both in windows and Linux systems. Would you please help to find out what's the problem?

**Comment by OshriHalimi** [comment]
Dear Xiang,
I added a matlab script with the name "prepare_test_scans_to_TF", in the folder: Learning Correspondence of Real Scans.

This script performs 1. remeshing of the scans to a lower resolution, 2. the calculation of the data for tensorflow and 3. the calculation of the geodesic distance matrix.

Note that you have to download the data of MPI-FAUST from the website and specify the path to the folder in the matlab script.

Best,
Oshri
