### ISSUE TITLE
Code for real scans.

### ISSUE THREAD

**Issue by lixiang-ucas** [OshriHalimi/unsupervised_learning_of_dense_shape_correspondence#2]
Dear @OshriHalimi and @orlitany,
     Thanks for sharing your code of this wonderful work. I'm trying to extend this work. Would you please share your code for real scans? Especially the code for the upscaling step to bring the correspondence back to the original resolution. I cannot find this part code in this repo as well as the DeepFunctionalMaps repo. 
Best,
Xiang

**Comment by OshriHalimi** [comment]
Dear Xiang,
The upscaling code is available in demo_upscaling under Tools folder.
